# render.yaml
services:
  - type: web
    name: videojuegos-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///database.db
      - key: SECRET_KEY
        value: dev-secret

  - type: static
    name: videojuegos-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: |
      cd frontend
      npm install
      npm run build
    publishDirectory: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://videojuegos-store.onrender.com
